name: pytorch-playground
channels:
  - defaults
  - pytorch
dependencies:
  - python==3.10
  - pytorch==1.12.0
  - torchtext==0.13.0
  - pip==21.2.4
  - matplotlib==3.5.2
  - pip:
    - numpy==1.23.0
    - transformers==4.22.2
    - botorch==0.8.1
    - gpytorch == 1.9.1
